from django.conf.urls import url, patterns
from django.contrib.auth.decorators import login_required, permission_required
from lambada import views
from lambada.views import TopicCreate, TopicDetail, TopicUpdate, TopicDelete, TopicList, PracticeBook, PracticeTopicDetail, PracticeDelete, PracticeUpdate, CoachList

urlpatterns = patterns('',
		url(r'^$', views.dashboard),
		url(r'^register/$', views.register),
		url(r'^user_login/$', views.user_login),
		url(r'^user_logout/$', views.user_logout),
		url(r'^forgot_login/$', views.forgot_login),
		url(r'^dashboard/$', views.dashboard),
		url(r'^topic/add/$', login_required(TopicCreate.as_view())),
		url(r'^topic/list/$', login_required(TopicList.as_view())),
		url(r'^topic/(?P<pk>[0-9]+)/$', login_required(TopicDetail.as_view())),
		url(r'^topic/(?P<pk>[0-9]+)/update/$', login_required(TopicUpdate.as_view())),
		url(r'^topic/(?P<pk>[0-9]+)/publish/$', views.topic_publish),
		url(r'^topic/(?P<pk>[0-9]+)/delete/$', login_required(TopicDelete.as_view())),
#		url(r'^practice/list/$', login_required(PracticeList.as_view())),
		url(r'^practice/list/$',views.practice_list), 
		url(r'^practice/next_speaking_error/$',views.next_speaking_error), 
		url(r'^practice/next_writing_error/$',views.next_writing_error), 
		url(r'^practice/book/$', login_required(PracticeBook.as_view())),
		url(r'^practice/book/payment/(?P<pk>[0-9]+)/$', views.practice_payment),
		url(r'^practice/topic/(?P<pk>[0-9]+)/$', login_required(PracticeTopicDetail.as_view())),
#		url(r'^practice/(?P<pk>[0-9]+)/$', login_required(PracticeDetail.as_view())),
		url(r'^practice/(?P<pk>[0-9]+)/$', views.practice_detail),
		url(r'^practice/(?P<pk>[0-9]+)/add/$', views.practice_add),
		url(r'^practice/(?P<pk>[0-9]+)/delete/$', login_required(PracticeDelete.as_view())),
		url(r'^practice/(?P<pk>[0-9]+)/update/$', login_required(PracticeUpdate.as_view())),
		url(r'^practice/(?P<pk>[0-9]+)/add_writing/$', views.practice_add_writing),
		url(r'^practice/(?P<pk>[0-9]+)/speaking_error_notification/$', views.speaking_error_notification),
		url(r'^practice/(?P<pk>[0-9]+)/report/speaking-review/$', views.practice_report_speaking_review),
		url(r'^practice/(?P<pk>[0-9]+)/report/writing-review/$', views.practice_report_writing_review),
		url(r'^practice/(?P<pk>[0-9]+)/report/speaking-publish/$', views.practice_report_speaking_publish),
		url(r'^practice/(?P<pk>[0-9]+)/report/writing-publish/$', views.practice_report_writing_publish),
		url(r'^defaultchannellog/download/(?P<pk>[0-9]+)/$', views.defaultChannel_log_download),
		url(r'^privatechannellog/download/(?P<pk>[0-9]+)/$', views.privateChannel_log_download),
		url(r'^coach/list/$', login_required(CoachList.as_view())),
		url(r'^coach/practice/(?P<pk>[0-9]+)/$', views.coach_practice_detail),
		url(r'^coach/practice/(?P<pk>[0-9]+)/cancel/$', views.coach_practice_cancel),
		url(r'^report/(?P<pk>[0-9]+)/report_add_speech/$', views.report_add_speech),
		url(r'^report/(?P<pk>[0-9]+)/report_add_speech_correction/$', views.report_add_speech_correction),
		url(r'^report/(?P<pk>[0-9]+)/speaking/$', views.report_speaking),
		url(r'^report/(?P<pk>[0-9]+)/report_add_writing/$', views.report_add_writing),
		url(r'^report/(?P<pk>[0-9]+)/report_add_writing_correction/$', views.report_add_writing_correction),
		url(r'^report/(?P<pk>[0-9]+)/writing/$', views.report_writing),
		url(r'^report/(?P<pk>[0-9]+)/report_add_speech_error/$', views.report_add_speech_error),
		url(r'^report/(?P<pk>[0-9]+)/report_delete_speech_error/$', views.report_delete_speech_error),
		url(r'^report/report_delete_writing_correction/$', views.report_delete_writing_correction),
		url(r'^report/(?P<pk>[0-9]+)/recording_correction_upload/$', views.recording_correction_upload, name='recording_correction_upload'),
		url(r'^recording/upload/(?P<pk>[0-9]+)/(?P<partNum>[0-9]+)/$', views.recording_upload, name='recording_upload'),
#		url(r'^report/add/(?P<pk>[0-9]+)/$', views.report_create, name='report_add'),
#		url(r'^recording/correction/(?P<pk>[0-9]+)/download/$', views.recording_correction_download, name='recording_correction_download'),
#		url(r'^recording/download/(?P<pk>[0-9]+)/$', views.recording_download, name='recording_download'),
#		url(r'^practice/private_channel_write/(?P<pk>[0-9]+)/$', views.private_channel_write),
#		url(r'^practice/default_channel_write/(?P<pk>[0-9]+)/$', views.default_channel_write),
#		url(r'^practice/private_channel_check/(?P<pk>[0-9]+)/$', views.private_channel_check),
#		url(r'^practice/default_channel_check/(?P<pk>[0-9]+)/$', views.default_channel_check, name='default_channel_check'),
)
